CREATE DATABASE IF NOT EXISTS joj_dakar CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE joj_dakar;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'Visiteur',
  country VARCHAR(100) NOT NULL DEFAULT 'Sénégal',
  country_code CHAR(2) NOT NULL DEFAULT 'SN',
  phone VARCHAR(30),
  accreditation VARCHAR(30) NOT NULL UNIQUE,
  avatar VARCHAR(10) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS wallets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL UNIQUE,
  balance DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  joj_points INT NOT NULL DEFAULT 0,
  card_number VARCHAR(20) NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS transactions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  tx_ref VARCHAR(30) NOT NULL UNIQUE,
  type ENUM('credit','debit') NOT NULL,
  label VARCHAR(255) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  icon VARCHAR(60) NOT NULL DEFAULT 'card-outline',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tickets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  ticket_ref VARCHAR(30) NOT NULL,
  event_name VARCHAR(255) NOT NULL,
  venue VARCHAR(255) NOT NULL,
  event_date VARCHAR(50) NOT NULL,
  event_time VARCHAR(20) NOT NULL,
  seat VARCHAR(100) NOT NULL,
  category ENUM('VIP','General','Transport','Accreditation') NOT NULL DEFAULT 'General',
  status ENUM('active','upcoming') NOT NULL DEFAULT 'upcoming',
  icon VARCHAR(60) NOT NULL DEFAULT 'ticket-outline',
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS events (
  id INT AUTO_INCREMENT PRIMARY KEY,
  event_ref VARCHAR(10) NOT NULL UNIQUE,
  sport VARCHAR(60) NOT NULL,
  match_name VARCHAR(255) NOT NULL,
  home_code CHAR(2) NOT NULL DEFAULT '',
  away_code CHAR(2) NOT NULL DEFAULT '',
  venue VARCHAR(255) NOT NULL,
  event_time VARCHAR(10) NOT NULL,
  event_date VARCHAR(20) NOT NULL,
  status ENUM('upcoming','live','finished') NOT NULL DEFAULT 'upcoming',
  category VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS live_scores (
  id INT AUTO_INCREMENT PRIMARY KEY,
  score_ref VARCHAR(10) NOT NULL UNIQUE,
  sport VARCHAR(60) NOT NULL,
  home_team VARCHAR(100) NOT NULL,
  away_team VARCHAR(100) NOT NULL,
  home_code CHAR(2) NOT NULL,
  away_code CHAR(2) NOT NULL,
  home_score INT NOT NULL DEFAULT 0,
  away_score INT NOT NULL DEFAULT 0,
  period VARCHAR(20) NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS medals (
  id INT AUTO_INCREMENT PRIMARY KEY,
  country VARCHAR(100) NOT NULL,
  country_code CHAR(2) NOT NULL UNIQUE,
  gold INT NOT NULL DEFAULT 0,
  silver INT NOT NULL DEFAULT 0,
  bronze INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS notifications (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT,
  icon VARCHAR(60) NOT NULL,
  color VARCHAR(10) NOT NULL DEFAULT '#FF6B35',
  title VARCHAR(100) NOT NULL,
  body TEXT NOT NULL,
  is_read TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
